"""Write reports/eda.md: what is in train.csv / train_series.csv and how good the public report labels are.

    python src/eda.py
"""
import re
from pathlib import Path

import pandas as pd
from sklearn.metrics import roc_auc_score

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
EXT = ROOT / "data" / "ext"

# Public report-derived label sets (Kaggle datasets, CC0), downloaded into data/ext/
LABEL_SETS = {
    "stevenleehans · llm_labels_v4_blend": "rsna-knee-llm-report-labels/llm_labels_v4_blend.csv",
    "stevenleehans · llm_labels_v2": "rsna-knee-llm-report-labels/llm_labels_v2.csv",
    "pilkwang · report_labels_v2": "rsna-knee-llm-labels/report_labels_v2.csv",
    "lixin73 · gpt56sol": "rsna-knee-llm-report-labels-sol56/labels_llm_gpt56sol.csv",
}

# Words that identify a report's language (good enough for a breakdown, not a real detector)
LANG_HINTS = [
    ("Greek", r"[α-ωΑ-Ω]"),
    ("Thai", r"[฀-๿]"),
    ("Chinese", r"[一-鿿]"),
    ("Cyrillic (Bulgarian, Mongolian)", r"[а-яА-Я]"),
    ("German", r"\b(Kniegelenk|Befund|Innenmeniskus|Erguss|Beurteilung)\b"),
    ("Dutch", r"\b(Bevindingen|meniscus|Besluit|knie)\b.*\b(van|de|het)\b"),
    ("Turkish", r"\b(diz|menisk|Sonuç|bulgular|eklem)\b"),
    ("Spanish", r"\b(rodilla|menisco|derrame|Impresión|rotura)\b"),
    ("Portuguese", r"\b(joelho|menisco|derrame articular|Impressão)\b"),
    ("Italian", r"\b(ginocchio|versamento|menisco|legamento)\b"),
    ("French", r"\b(genou|ménisque|épanchement)\b"),
    ("Croatian/Bosnian", r"\b(koljen|menisk|izljev)\w*"),
    ("English", r"\b(the|meniscus|effusion|ligament)\b"),
]


def language(report):
    for lang, pat in LANG_HINTS:
        if re.search(pat, report, flags=re.IGNORECASE):
            return lang
    return "other"


def md_table(df, floatfmt="{:.3f}"):
    df = df.copy()
    for c in df.columns:
        if df[c].dtype.kind == "f":
            df[c] = df[c].map(floatfmt.format)
    head = "| " + " | ".join(map(str, df.columns)) + " |"
    sep = "|" + "---|" * len(df.columns)
    rows = ["| " + " | ".join(map(str, r)) + " |" for r in df.itertuples(index=False)]
    return "\n".join([head, sep, *rows])


def main():
    train = pd.read_csv(RAW / "train.csv")
    series = pd.read_csv(RAW / "train_series.csv")
    labels = list(train.columns[2:])
    gold = train.dropna(subset=labels).set_index("StudyInstanceUID")[labels].astype(int)

    out = ["# EDA · RSNA Knee Abnormality Detection", "", "Generated by `python src/eda.py`.", ""]

    out += ["## Size", "",
            f"- **{len(train):,}** training studies, **{len(series):,}** series "
            f"(median {series.groupby('StudyInstanceUID').size().median():.0f} series per study).",
            f"- Only **{len(gold)}** studies carry the twelve labels; every study has a report "
            f"(median {train.Report.str.len().median():.0f} characters).",
            "- About 1,300 hidden test studies, **without reports**: the model must work from images alone.", ""]

    prev = pd.DataFrame({"label": labels, "positives": gold.sum().values,
                         "prevalence": gold.mean().values})
    out += ["## Labels on the 58 gold studies", "", md_table(prev, "{:.2f}"), "",
            "Prevalence is high (balanced on purpose), so these 58 are not a sample of the real distribution.", ""]

    langs = train.Report.map(language).value_counts()
    out += ["## Report languages (keyword heuristic)", "",
            md_table(pd.DataFrame({"language": langs.index, "studies": langs.values})), ""]

    combo = (series.groupby(["Anatomical_Plane", "Fluid_Sensitive", "Fat_Suppression"]).size()
             .rename("series").reset_index())
    per_study = series.groupby("StudyInstanceUID").Anatomical_Plane.agg(lambda s: frozenset(s))
    out += ["## Series", "", md_table(combo), "",
            f"- {(per_study.map(len) == 3).mean():.1%} of studies have all three planes "
            f"(sagittal, coronal, axial).",
            "- Fluid-sensitive and fat-suppressed are almost always the same flag in train.", ""]

    rows = []
    for name, rel in LABEL_SETS.items():
        path = EXT / rel
        if not path.exists():
            continue
        d = pd.read_csv(path).set_index("StudyInstanceUID").reindex(gold.index)
        aucs = {c: roc_auc_score(gold[c], d[c].fillna(0.5)) for c in labels if c in d}
        rows.append({"label set": name, "macro AUC vs gold": sum(aucs.values()) / len(aucs),
                     "weakest": min(aucs, key=aucs.get), "weakest AUC": min(aucs.values())})
    if rows:
        out += ["## Public report labels vs the 58 gold labels", "",
                md_table(pd.DataFrame(rows)), "",
                "Report labels cap out near **0.89 AUC** against the radiologists' image-based labels, "
                "and rank-blending several sets does not raise that. Synovitis is the weakest finding: "
                "reports rarely mention it.", ""]

    (ROOT / "reports").mkdir(exist_ok=True)
    (ROOT / "reports" / "eda.md").write_text("\n".join(out))
    print("\n".join(out))


if __name__ == "__main__":
    main()
