"""Score every trained fold on the 58 gold studies and write reports/gold_scores.md.

Reads data/runs/<kernel>/gold_<tag>.csv (downloaded with `kaggle kernels output`), scores each
checkpoint alone, then greedily adds checkpoints to a rank-average while the gold macro AUC rises.
58 studies is a small sample, so treat differences under ~0.01 as noise.

    python src/evaluate.py
"""
from pathlib import Path

import pandas as pd
from sklearn.metrics import roc_auc_score

ROOT = Path(__file__).resolve().parents[1]


def macro_auc(gold, pred):
    return sum(roc_auc_score(gold[c], pred[c]) for c in gold.columns) / len(gold.columns)


def rank_mean(preds):
    return sum(p.rank(pct=True) for p in preds) / len(preds)


def main():
    train = pd.read_csv(ROOT / "data" / "raw" / "train.csv")
    labels = list(train.columns[2:])
    gold = train.dropna(subset=labels).set_index("StudyInstanceUID")[labels].astype(int)

    preds = {}
    for f in sorted((ROOT / "data" / "runs").glob("*/gold_*.csv")):
        preds[f"{f.parent.name}/{f.stem[5:]}"] = pd.read_csv(f).set_index("StudyInstanceUID").loc[gold.index, labels]
    single = pd.Series({k: macro_auc(gold, p) for k, p in preds.items()}).sort_values(ascending=False)

    chosen, best = [], 0.0
    for k in single.index:  # greedy forward selection, strongest first
        score = macro_auc(gold, rank_mean([preds[c] for c in chosen + [k]]))
        if score > best:
            chosen, best = chosen + [k], score

    out = ["# Gold-58 scores", "", "Generated by `python src/evaluate.py`.", "",
           "| Checkpoint | Gold macro AUC |", "|---|---|"]
    out += [f"| {k} | {v:.4f} |" for k, v in single.items()]
    out += ["", f"**Greedy rank-average ({len(chosen)} checkpoints): {best:.4f}**", ""]
    out += [f"- {k}" for k in chosen]
    (ROOT / "reports" / "gold_scores.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
