"""Generate a Kaggle GPU kernel that trains two folds of my reader at once, one per T4.

The kernel writes src/knee.py and src/train.py to /kaggle/working/src and runs
`train.py --fold A` on GPU 0 and `--fold B` on GPU 1 in parallel.

    python src/make_train_kernel.py --name k03b-effv2s --folds 0 1 -- --epochs 8
    kaggle kernels push -p kernels/k03b-effv2s
"""
import argparse
import base64
import json
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
USER = "sinhaaditya5"
CACHES = {256: [f"{USER}/rsna-knee-k02-cache256-s{s}" for s in range(4)],
          384: [f"{USER}/rsna-knee-k09-cache384-s{s}" for s in range(6)]}
LABEL_DATASETS = ["stevenleehans/rsna-knee-llm-report-labels"]

RUNNER = '''
import base64, json, os, subprocess, sys, traceback, zlib
# Everything runs inside try/except and the kernel always exits cleanly: Kaggle keeps no log and no
# output files for a kernel that errors, so a failure is recorded in /kaggle/working/error.txt instead.
try:
    print("runner start", sys.version, flush=True)
    os.makedirs("/kaggle/working/src", exist_ok=True)
    for name, code in json.loads(zlib.decompress(base64.b64decode(SOURCES))).items():
        with open(f"/kaggle/working/src/{{name}}", "w") as f:
            f.write(code)
    procs = []
    for gpu, fold in enumerate({folds}):
        env = dict(os.environ, CUDA_VISIBLE_DEVICES=str(gpu), PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True")
        cmd = [sys.executable, "-u", "/kaggle/working/src/train.py", "--fold", str(fold), "--workers", "2"] + {extra}
        log = open(f"/kaggle/working/train_f{{fold}}.log", "w")
        procs.append((fold, subprocess.Popen(cmd, env=env, stdout=log, stderr=subprocess.STDOUT), log))
    print("launched folds", [f for f, _, _ in procs], flush=True)
    codes = []
    for fold, p, log in procs:
        codes.append(p.wait())
        log.close()
        print(f"===== fold {{fold}} exit {{p.returncode}}", flush=True)
        print(open(f"/kaggle/working/train_f{{fold}}.log").read()[-4000:], flush=True)
    if any(codes):
        raise RuntimeError(f"fold exit codes {{codes}}")
except BaseException:
    traceback.print_exc(file=sys.stdout)
    open("/kaggle/working/error.txt", "w").write(traceback.format_exc())
'''


def pack(sources):
    """Source files as one base64 string: plain ASCII, nothing for Kaggle's script parser to trip on."""
    return base64.b64encode(zlib.compress(json.dumps(sources).encode())).decode()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--folds", type=int, nargs=2, default=[0, 1])
    ap.add_argument("--cache", type=int, default=256, choices=sorted(CACHES), help="cache kernels to attach")
    ap.add_argument("extra", nargs="*", help="arguments passed through to train.py (after --)")
    args = ap.parse_args()

    sources = {n: (ROOT / "src" / n).read_text() for n in ["knee.py", "train.py"]}
    code = (f"# Trains folds {args.folds} of my knee reader on 2x T4. Generated by src/make_train_kernel.py.\n"
            f"SOURCES = {pack(sources)!r}\n" + RUNNER.format(folds=args.folds, extra=args.extra + ["--cache", str(args.cache)]))
    d = ROOT / "kernels" / args.name
    d.mkdir(parents=True, exist_ok=True)
    # A notebook, not a script: script kernels on GPU kept dying within seconds with no log,
    # while every notebook kernel started fine.
    cell = {"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None,
            "source": code.splitlines(keepends=True)}
    nb = {"cells": [cell], "metadata": {"kernelspec": {"name": "python3", "display_name": "Python 3",
                                                       "language": "python"}},
          "nbformat": 4, "nbformat_minor": 4}
    for old in d.glob("train_kernel.py"):
        old.unlink()
    (d / "train_kernel.ipynb").write_text(json.dumps(nb, indent=1))
    meta = {
        "id": f"{USER}/rsna-knee-{d.name}",
        "title": f"rsna-knee-{d.name}",
        "code_file": "train_kernel.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": True,
        "enable_tpu": False,
        "enable_internet": True,  # pretrained backbone weights from the Hugging Face hub
        "machine_shape": "NvidiaTeslaT4",
        "dataset_sources": LABEL_DATASETS,
        "competition_sources": ["rsna-knee-abnormality-detection"],
        "kernel_sources": CACHES[args.cache],
        "model_sources": [],
    }
    (d / "kernel-metadata.json").write_text(json.dumps(meta, indent=2) + "\n")
    print("wrote", d)


if __name__ == "__main__":
    main()
