"""Generate a Kaggle GPU kernel that trains two folds of my reader at once, one per T4.

The kernel writes src/knee.py and src/train.py to /kaggle/working/src and runs
`train.py --fold A` on GPU 0 and `--fold B` on GPU 1 in parallel.

    python src/make_train_kernel.py --name k03-effv2s --folds 0 1 -- --epochs 8
    kaggle kernels push -p kernels/k03-effv2s-f01
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
USER = "sinhaaditya5"
CACHE_KERNELS = [f"{USER}/rsna-knee-k02-cache256-s{s}" for s in range(4)]
LABEL_DATASETS = ["stevenleehans/rsna-knee-llm-report-labels"]

RUNNER = '''
import os, subprocess, sys
os.makedirs("/kaggle/working/src", exist_ok=True)
for name, code in SOURCES.items():
    with open(f"/kaggle/working/src/{{name}}", "w") as f:
        f.write(code)
procs = []
for gpu, fold in enumerate({folds}):
    env = dict(os.environ, CUDA_VISIBLE_DEVICES=str(gpu))
    cmd = [sys.executable, "-u", "/kaggle/working/src/train.py", "--fold", str(fold), "--workers", "2"] + {extra}
    log = open(f"/kaggle/working/train_f{{fold}}.log", "w")
    procs.append((fold, subprocess.Popen(cmd, env=env, stdout=log, stderr=subprocess.STDOUT), log))
for fold, p, log in procs:
    p.wait()
    log.close()
    print(f"===== fold {{fold}} exit {{p.returncode}}")
    print(open(f"/kaggle/working/train_f{{fold}}.log").read()[-4000:])
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--folds", type=int, nargs=2, default=[0, 1])
    ap.add_argument("extra", nargs="*", help="arguments passed through to train.py (after --)")
    args = ap.parse_args()

    sources = {n: (ROOT / "src" / n).read_text() for n in ["knee.py", "train.py"]}
    code = (f"# Trains folds {args.folds} of my knee reader on 2x T4. Generated by src/make_train_kernel.py.\n"
            f"SOURCES = {sources!r}\n" + RUNNER.format(folds=args.folds, extra=args.extra))
    d = ROOT / "kernels" / f"{args.name}-f{args.folds[0]}{args.folds[1]}"
    d.mkdir(parents=True, exist_ok=True)
    (d / "train_kernel.py").write_text(code)
    meta = {
        "id": f"{USER}/rsna-knee-{d.name}",
        "title": f"rsna-knee-{d.name}",
        "code_file": "train_kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_tpu": False,
        "enable_internet": True,  # pretrained backbone weights from the Hugging Face hub
        "machine_shape": "NvidiaTeslaT4",
        "dataset_sources": LABEL_DATASETS,
        "competition_sources": ["rsna-knee-abnormality-detection"],
        "kernel_sources": CACHE_KERNELS,
        "model_sources": [],
    }
    (d / "kernel-metadata.json").write_text(json.dumps(meta, indent=2) + "\n")
    print("wrote", d)


if __name__ == "__main__":
    main()
